export const ALIYUN_ACCESS_KEY_ID = process.env.NEXT_PUBLIC_ALIYUN_ACCESS_KEY_ID ?? ''
export const ALIYUN_ACCESS_KEY_SECRET = process.env.NEXT_PUBLIC_ALIYUN_ACCESS_KEY_SECRET ?? ''
export const ALIYUN_OSS_BUCKET = process.env.NEXT_PUBLIC_ALIYUN_OSS_BUCKET ?? ''
export const ALIYUN_OSS_REGION = process.env.NEXT_PUBLIC_ALIYUN_OSS_REGION ?? ''
